@startuml TERM2
title インターネットTV

' ====================
' 番組・ジャンル系
' ====================
entity "番組マスタ" as show_master {
    + show_id : int
    --
    show_name : string
    show_detail : string  
}

entity "ジャンルマスタ" as genre_master{
    + genre_id : int
    --
    genre_name : string
}

entity "番組ジャンル関連" as show_genre {
    + show_id : int
    + genre_id : int
}

' ====================
' シーズン・エピソード系
' ====================
entity "シーズンマスタ" as season_master {
    + season_id : int
    --
    show_id : int
    season_name : string
}

entity "エピソードマスタ" as episode_master{
    + episode_id : int
    --
    season_id : int
    episode_name : string
    episode_detail : string
    episode_length : int
    episode_release_date : datetime
}

' ====================
' 時間・チャンネル系
' ====================
entity "時間マスタ" as time_master {
    + time_id : int
    --
    broadcast_start : datetime
    broadcast_end   : datetime
}

entity "チャンネルマスタ" as ch_master {
    + ch_id : int
    --
    ch_name : string
}

entity "時間チャンネル関連" as broadcast_ch{
    + time_id : int
    + ch_id : int
    --
    episode_id : int
}

' ====================
' 視聴実績系
' ====================
entity "視聴情報" as view_info {
   + view_id : int
   --
   episode_id : int
   view_cnt : int
}

' ====================
' リレーション
' ====================
show_master   ||--o{ season_master
season_master||--o{ episode_master

episode_master ||--o{ broadcast_ch
time_master ||--o{ broadcast_ch
ch_master ||--o{ broadcast_ch

episode_master ||--o{ view_info

show_master ||--|{ show_genre
genre_master ||--o{ show_genre

@enduml
