@startuml TERM2
title インターネットTV

' ====================
' 番組・ジャンル系
' ====================
entity "番組" as program {
    + program_id : int
    --
    program_title : string
    program_detail : string  
}

entity "ジャンル" as genre{
    + genre_id : int
    --
    genre_name : string
}

entity "番組ジャンル関連" as program_genre {
    + program_id : int
    + genre_id : int
}

' ====================
' シーズン・エピソード系
' ====================
entity "シーズン" as season {
    + season_id : int
    --
    program_id : int
    season_no : int
}

entity "エピソード" as episode{
    + episode_id : int
    --
    season_id : int
    episode_no : int
    episode_title : string
    episode_detail : string
    episode_length : int
    episode_release_date : datetime
}

' ====================
' チャンネル系
' ====================

entity "チャンネル" as channel {
    + channel_id : int
    --
    channel_name : string
}

' ====================
' 放送情報系
' ====================

entity "放送情報" as broadcast {
    + broadcast_id : int
    --
    broadcast_start : datetime
    broadcast_end   : datetime
    channel_id : int
    episode_id : int
}

' ====================
' 視聴実績系
' ====================
entity "視聴情報" as view_info {
   + view_id : int
   --
   broadcast_id : int
   view_cnt : int
   
}

' ====================
' リレーション
' ====================
program   ||--|{ season
season||--|{ episode

episode ||--o{ broadcast
channel ||--o{ broadcast

broadcast ||--|| view_info

program ||--|{ program_genre
genre ||--o{ program_genre

@enduml
